language: python
python:
  - 2.7
sudo: false

env:
    - TEST_DIR="tests"

# Setup anaconda
before_install:
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda-3.8.3-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-3.8.3-Linux-x86_64.sh -O miniconda.sh; fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/anaconda/bin:/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  - pip install --upgrade pip

install:
  # - conda install --yes pip python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib ipywidgets
  # - git clone https://github.com/simpeg/simpeg.git
  # - cd simpeg; git checkout dev; git pull; python setup.py build_ext --inplace; cd ..
  # - export PATH=$PWD:$PATH
  # - export PYTHONPATH=$PWD:$PYTHONPATH

  - python setup.py install
  - echo $PWD
  - cd ../
  - git clone https://github.com/geoscixyz/em_apps.git
  - cd em_examples
  - echo $PWD

# Run test
script:
  - nosetests $TEST_DIR

notifications:
  slack: ubcgif:1Z2lR3XYRSM3GHflG71ZHEN6
