language: python
python:
  - 2.7
  - 3.6

sudo: false

env:
    - TEST_DIR="tests"

# Setup anaconda
before_install:
  - pip install --upgrade pip;
  - pip install -r requirements.txt

# Run test
script:
  - nosetests $TEST_DIR

notifications:
  slack: ubcgif:1Z2lR3XYRSM3GHflG71ZHEN6
