language: python
python:
  - 2.7
sudo: false

env:
    - TEST_DIR="tests"

# Setup anaconda
before_install:
  - pip install --upgrade pip;
  - pip install -r requirements.txt
  - python setup.py install
  # - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda-3.8.3-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-3.8.3-Linux-x86_64.sh -O miniconda.sh; fi
  # - chmod +x miniconda.sh
  # - ./miniconda.sh -b
  # - export PATH=/home/travis/anaconda/bin:/home/travis/miniconda/bin:$PATH
  # - conda update --yes conda

install:
  # - conda install --yes pip python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib ipywidgets
  - git clone https://github.com/simpeg/simpeg.git
  - cd simpeg; git checkout dcip/dev; git pull; python setup.py build_ext --inplace; cd ..
  - export PATH=$PWD/simpeg:$PATH
  - export PATH=$PWD/em_examples:$PATH

# Run test
script:
  - nosetests $TEST_DIR

notifications:
  email:
    - lindseyheagy@gmail.com
