name: geosci-labs

channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - scipy
  - matplotlib
  - Pillow
  - ipywidgets>=0.6.0
  - requests
  - mkl
  - pip:
    - pymatsolver
    - discretize
    - deepdish
    - SimPEG
    - empymod
    - git+https://github.com/wwzzyyzzrr/geosci-labs
