name: geosci-labs-dev

channels:
  - conda-forge
dependencies:
  - cvxopt
  - deepdish
  - discretize
  - ipywidgets>=0.6.0
  - jupyter
  - matplotlib=3.4.3
  - Pillow
  - pip
  - pymatsolver
  - requests
  - SimPEG==0.23.0
  - pytest
  - flake8
  - black
  - pip:
    - testipynb

