name: em_examples

dependencies:
  - python=2.7
  - numpy
  - scipy
  - matplotlib
  - pip:
    - git+git://github.com/simpeg/simpeg.git@master#egg=simpeg
    - git+git://github.com/simpeg/simpegdc.git@Dom_Dev#egg=simpegdc
