name: em_examples

dependencies:
  - python=2.7
  - numpy
  - scipy
  - matplotlib
  - pip:
    - git+https://github.com/simpeg/simpeg.git@Examples
    - git+https://github.com/simpeg/simpegDC.git@Dom_Dev